language: java
jdk:
  - oraclejdk8
install:
  - mvn validate  # install .jar files
# - mvn install -DskipTests=true

after_success:
  - mvn clean test jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN