language: java
jdk:
  - oraclejdk8
install:
  - mvn validate  # install .jar files
# - mvn install -DskipTests=true

after_success:
  - mvn test jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN
  # - (curl https://www.jpm4j.org/install/script | sh) && jpm install com.codacy:codacy-coverage-reporter:assembly && codacy-coverage-reporter -l Java -r coverage.xml
  - codacy-coverage-reporter -l Java -r coverage.xml