language: java
jdk:
  - oraclejdk8

before_install:
  - pwd
  - 'ls target || (echo "no target dir" && ls)'
install:
  - mvn validate  # install .jar files

after_success:
  - pwd
  - 'ls target'
  #
  # coveralls.io
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] &&  mvn clean test jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN'
  #
  # codacy
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && (pip install codacy-coverage && python-codacy-coverage -r site/jacoco/jacoco.xml || (mkdir --parents target/jpm && curl -sL https://bndtools.ci.cloudbees.com/job/bnd.master/lastSuccessfulBuild/artifact/biz.aQute.jpm/generated/biz.aQute.jpm.run.jar > target/jpm/jpm4j.jar && java -jar target/jpm/jpm4j.jar -u init && export PATH=$PATH:$HOME/jpm/bin && jpm install com.codacy:codacy-coverage-reporter:assembly && codacy-coverage-reporter -l Java -r site/jacoco/jacoco.xml ))'